# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/d2x/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),d2x)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-N976B,b72d96cfd138378fa8e39699a2e0b55d42fe5d12)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-N976N,b1daf3c653d44edf2770db88068a3323a5892963)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-N976B,52b98f3fd1146a38b526e5525de731af90282367)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-N976N,09d28e23d83bd646ff160b9efc132605d65f1ec6)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-N976B,e201aee79b9a014131500b13fe82fc4b8ab46a5f)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-N976N,d6e6a0f3852fad3eae4638faa9e4a34d409c9542)
$(call add-radio-file-sha1-checked,radio/models,3355889615e4a8ae46a6218e5c266655cc079cd9)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-N976B,4983d67b854b2b9dc0dcded9d4cff8f3659a4f2c)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-N976N,81a40685470378df5b94a1a31a56a41200977db1)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-N976B,ce042e138b05b326d0e8303f9bdde08809bcad8c)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-N976N,d993aaed638c9d981d99f31fd890de36fd7e660c)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-N976B,161b9e8fc88ffdb5b786e5daf2d86aa30f2f5d58)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-N976N,229a8d6bb71bee8f1e33f46d125767c2135303b4)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-N976B,c641edbbe7827f3a3b87fdebe00d36614f59f53a)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-N976N,0c5cb42c1668adc31122fd8d62f93143969130bb)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-N976B,5dd7aee1a9814277f723e5a63cb8ca5d0c514ba6)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-N976N,945181127bacbe37de94503c65b9ef37f00cb6fa)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-N976B,1250e810f141e072376441b6aebc74e70c434129)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-N976N,91fdce37075c25f9ee6359b63308f21a2695df19)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-N976B,4af254aed5585f8a8783ec98295720d380521bad)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-N976N,b382357b7b52b56b5b84e3abd81b26d6de25a544)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-N976B,65d41d04666b61a052b0acfb0f4bbe8d744d26e8)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-N976N,8f139b9d6d1521263dc6e867f6bdedb37fb2438b)
$(call add-radio-file-sha1-checked,radio/version_SM-N976B,0b6e72417c3565b76a74dfd68602ebfe482b3640)
$(call add-radio-file-sha1-checked,radio/version_SM-N976N,ea4ef8cb88464d98f5b619c3a510b3d41bce916b)

endif
